# Generated by Django 4.1.7 on 2023-04-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
