# Generated by Django 4.1.7 on 2023-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_doctor_availability_remove_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
